### ISSUE TITLE
Package request: statsmodels

### ISSUE THREAD

**Issue by jdpmorgan** [holzschu/Carnets#100]
Thanks for your work 🙏

**Comment by sksy-in** [comment]
Unable to install statsmodels package, please include it in the default.

**Comment by sksy-in** [comment]
error that I get when I run %pip install statsmodels

ERROR: Command errored out with exit status 1:
   command: /private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/bin/python3 /private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/DE795128-F9B2-487C-BBB8-B90D530806CF/tmp/tmp9rsdrm9q
       cwd: /private/var/mobile/Containers/Data/Application/DE795128-F9B2-487C-BBB8-B90D530806CF/tmp/pip-install-k48qqznr/statsmodels_8cca781301a049418b0ad9c352c4192e
  Complete output (12 lines):
  Traceback (most recent call last):
    File "/private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 83, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/os.py", line 682, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/bin/python3 /private/var/containers/Bundle/Application/B7994B67-52D2-449A-B9F7-2C3E366D9605/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/DE795128-F9B2-487C-BBB8-B90D530806CF/tmp/tmp9rsdrm9q Check the logs for full command output.

**Comment by holzschu** [comment]
According to their webpage: https://www.statsmodels.org/stable/install.html statsmodel requires scipy and a C compiler.

I will give it a try after scipy has been done.
