### ISSUE TITLE
pip install issue (nexusforge)

### ISSUE THREAD

**Issue by slhill** [holzschu/Carnets#120]
I’m having trouble installing a package from pip (which is pure python and works everywhere else I have tried).

Any assistance would be very welcome.

 In [1]: !pip install nexusforge

Collecting nexusforge
  Downloading https://files.pythonhosted.org/packages/21/c8/e4eedefe0913e72d195933285403f86d2747a8f939cc702478d71c21264e/nexusforge-0.3.3.tar.gz (379kB)
     |████████████████████████████████| 389kB 1.8MB/s eta 0:00:01
Collecting hjson (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/8a/92/6b6b85064f8a88cb3b31901d839e7b45c33e4ee450bb1b3cf0c226cca8ec/hjson-3.0.1.tar.gz (43kB)
     |████████████████████████████████| 51kB 17.7MB/s eta 0:00:01
Requirement already satisfied: pyyaml in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages (from nexusforge) (5.1)
Requirement already satisfied: pandas in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pandas-0.24.2-py3.7-macosx-10.9-x86_64.egg (from nexusforge) (0.24.2)
Collecting nexus-sdk (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/1d/0c/354868778a580be31151dbb3ab6b309cc790523ba73021264dff1e789a72/nexus_sdk-0.3.2-py3-none-any.whl (45kB)
     |████████████████████████████████| 51kB 6.2MB/s eta 0:00:01
Collecting aiohttp (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl (441kB)
     |████████████████████████████████| 450kB 14.3MB/s eta 0:00:01
Collecting nest_asyncio (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/a0/44/f2983c5be9803b08f89380229997e92c4bdd7a4a510ccee565b599d1bdc8/nest_asyncio-1.4.0-py3-none-any.whl
Collecting pyLD (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/82/92/2e6b2756d9b6603a24630f9d3c795fa6add3ef5c7a87a6f7062d2e845a02/PyLD-2.0.3.tar.gz (70kB)
     |████████████████████████████████| 71kB 13.7MB/s eta 0:00:01
Collecting pyshacl==0.11.6.post1 (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/89/83/536a0d460ca702f04d7b0809691c0472bf7be04da89c861e949e2e7cef3f/pyshacl-0.11.6.post1-py3-none-any.whl (84kB)
     |████████████████████████████████| 92kB 12.2MB/s eta 0:00:01
Collecting rdflib-jsonld (from nexusforge)
  Downloading https://files.pythonhosted.org/packages/f5/17/45e137be0d93b70827fe5529c0400731344a978bc792193d7d9152e6dbe4/rdflib-jsonld-0.5.0.tar.gz (55kB)
     |████████████████████████████████| 61kB 18.2MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.5.0 in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages (from pandas->nexusforge) (2.7.5)
Requirement already satisfied: pytz>=2011k in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages (from pandas->nexusforge) (2018.9)
Requirement already satisfied: numpy>=1.12.0 in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg (from pandas->nexusforge) (1.16.0)
Collecting puremagic (from nexus-sdk->nexusforge)
  Downloading https://files.pythonhosted.org/packages/d5/6e/62d1cef9a0d8edf2d9c44b0a1b91b0b29b66fb693c94af278a0c76ddfd8c/puremagic-1.10-py3-none-any.whl
Requirement already satisfied: requests in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages (from nexus-sdk->nexusforge) (2.21.0)
Collecting sseclient (from nexus-sdk->nexusforge)
  Downloading https://files.pythonhosted.org/packages/b2/c9/734c8ed2ceb6c053a710833b8bf9f95fd4ae8ef4c8e63a165c9a09cfe172/sseclient-0.0.26.tar.gz
Collecting yarl<2.0,>=1.0 (from aiohttp->nexusforge)
  Downloading https://files.pythonhosted.org/packages/ac/dd/59768bb3fa08e8b23e91575bca3ff8d2edbfbceebec8c59eaa24c4215791/yarl-1.5.1.tar.gz (173kB)
     |████████████████████████████████| 174kB 8.8MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... -error

  ERROR: Complete output from command /var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/bin/python3 /var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/tmp/tmpk22jtzrp:
  ERROR: Traceback (most recent call last):
    File "/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute __getattr__
  ----------------------------------------
ERROR: Command "/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/bin/python3 /var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/tmp/tmpk22jtzrp" failed with error code 1 in /private/var/mobile/Containers/Data/Application/5964C031-6676-438F-B91E-D2D7F0432548/tmp/pip-install-spt1pawo/yarl

**Comment by holzschu** [comment]
Thank you for this detailed report. I was able to reproduce the issue. The short version is that one of the packages has updated setuptools, and the updated version won’t work. I’ll try to solved this ASAP.

**Comment by slhill** [comment]
Excellent - thanks for the quick response. Fingers crossed that it’s not too hard to fix!

**Comment by Downchuck** [comment]
Ran into this as well -- seems to come from aiohttp - I hit it from a different set of dependencies

**Comment by holzschu** [comment]
Hi, 
assuming you've already installed aiohttp using the instructions from https://github.com/holzschu/Carnets/issues/128#issuecomment-733855004, "!pip install nexusforge" now works on the latest TestFlight version (soon to become the AppStore version).

It installs a *lot* of extra packages, and I haven't tested if the install works (but they usually do).
Also, the install of nexusforge is one of the rare Python packages that require 3 different python interpreters to run in parallel, so it won't work if you have multiple notebooks open. It's best to run the install on a fresh run of Carnets, before opening other notebooks.
