### ISSUE TITLE
Aiohttp broken

### ISSUE THREAD

**Issue by Downchuck** [holzschu/Carnets#128]
This seems specific to aiohttp, amongst various packages this is the only one I hit an issue with.

%pip install aiohttp

```ERROR: Command errored out with exit status 1:
   command: /var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/bin/python3 /var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/tmp/tmp7hnuznmm
       cwd: /private/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/tmp/pip-install-ahquj85c/aiohttp
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute __getattr__
  ----------------------------------------
ERROR: Command errored out with exit status 1: /var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/bin/python3 /var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/356CB2FC-E501-4E6B-8526-67F1EED197BC/tmp/tmp7hnuznmm Check the logs for full command output.
```

**Comment by holzschu** [comment]
Thank you for raising it. I'm going to have a look.

**Comment by holzschu** [comment]
Hi, 
it's not obvious from the error message, but aiohttp has some Cython components, which require a C compiler to install (and there are no C compilers on iOS, for the time being). This is probably what's causing the error message.

**Comment by holzschu** [comment]
For my records: the same issue was raised in a-Shell: https://github.com/holzschu/a-shell/issues/130

**Comment by holzschu** [comment]
Hi, 
you can install a pure-python version of aiohttp with: 
```
!setenv YARL_NO_EXTENSIONS 1
!setenv MULTIDICT_NO_EXTENSIONS 1
!pip install aiohttp --no-use-pep517
```

**Comment by Downchuck** [comment]
@holzschu That one worked -- should I close out the issue? I could reopen if I see something further in the stack -- really appreciate the work you've done to push python access forward on the ipad.

**Comment by holzschu** [comment]
I would say let's leave it open. Someone else might need aiohttp, and the solution is not completely obvious.

**Comment by holzschu** [comment]
I've modified Carnets so these environment variables are set by default, so "pip install aiohttp" now works.
