### ISSUE TITLE
Can’t pip install prettytable

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#129]
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/subprocess.py", line 73, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 18, in <module>
    from distutils.util import strtobool
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/distutils/util.py", line 14, in <module>
    from distutils.spawn import spawn
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/distutils/spawn.py", line 11, in <module>
    import subprocess
  File "/private/var/containers/Bundle/Application/AFB2E12F-462D-46EF-A988-B81BAE71430D/Carnets.app/Library/lib/python3.9/subprocess.py", line 78, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'

**Comment by holzschu** [comment]
Hi, 
that's not related to prettytable, that's a different bug that I am tracking (it affects both a-Shell and Carnets). Repeating the command makes it work, eventually.
