### ISSUE TITLE
Not able to install discord module with pip install discord

### ISSUE THREAD

**Issue by AnujKuralkar** [holzschu/Carnets#141]
pip install discord

Defaulting to user installation because normal site-packages is not writeable
Collecting discord
  Using cached discord-1.0.1-py3-none-any.whl (1.1 kB)
Collecting discord.py>=1.0.1
  Using cached discord.py-1.5.1-py3-none-any.whl (701 kB)
Collecting aiohttp<3.7.0,>=3.6.0
  Using cached aiohttp-3.6.3.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... -error

  ERROR: Command errored out with exit status 1:
   command: /private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/bin/python3 /private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/2CDA65D6-FEF1-4AD7-9718-E1ED8ACCDCBA/tmp/tmpihdzfp1u
       cwd: /private/var/mobile/Containers/Data/Application/2CDA65D6-FEF1-4AD7-9718-E1ED8ACCDCBA/tmp/pip-install-ohkn35l_/aiohttp_b380ce2c45874f6bb41d061567849077
  Complete output (12 lines):
  Traceback (most recent call last):
    File "/private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 83, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/os.py", line 682, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/bin/python3 /private/var/containers/Bundle/Application/B78BE3AE-0D0C-476D-B45C-8FDC903B9464/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/2CDA65D6-FEF1-4AD7-9718-E1ED8ACCDCBA/tmp/tmpihdzfp1u Check the logs for full command output.

Note: you may need to restart the kernel to use updated packages.

**Comment by holzschu** [comment]
Hi, 
the main problem comes from aiohttp. The solution from issue #128 works here too: 
```
!setenv YARL_NO_EXTENSIONS 1
!setenv MULTIDICT_NO_EXTENSIONS 1
!pip install discord --no-use-pep517
```
(long answer: `aiohttp` requires yarl and multidict, who have C modules, and pip tries to compile them. You need to tell pip that you don't want the C extensions, and also deactivate pep517)

**Comment by ryanwyu** [comment]
What if I encounter the same issue when install other packages such as seaborn, sklearn?

**Comment by holzschu** [comment]
seaborn and sklearn both require scipy, and scipy has a *lot* of C modules (80 of them), not to mention a few things written in Fortran. I am working on it, but it's not easy.
