### ISSUE TITLE
Can not install scikit-image

### ISSUE THREAD

**Issue by zgw521** [holzschu/Carnets#203]
pip install scikit-image is not working, see below for detail on my iPad

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-image
  Using cached scikit-image-0.18.3.tar.gz (29.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /private/var/containers/Bundle/Application/07F5BD7B-283E-42BD-8F2D-9EE6B6772B46/Carnets-sci.app/Library/bin/python3 /private/var/containers/Bundle/Application/07F5BD7B-283E-42BD-8F2D-9EE6B6772B46/Carnets-sci.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/EEF85416-2409-4FDE-8D41-3256A66AB65C/tmp/tmpuf5hl0_1
       cwd: /private/var/mobile/Containers/Data/Application/EEF85416-2409-4FDE-8D41-3256A66AB65C/tmp/pip-install-ogni4yoi/scikit-image_4a079bc699874dc38c88d41823c558a9
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/private/var/containers/Bundle/Application/07F5BD7B-283E-42BD-8F2D-9EE6B6772B46/Carnets-sci.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/private/var/containers/Bundle/Application/07F5BD7B-283E-42BD-8F2D-9EE6B6772B46/Carnets-sci.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/private/var/containers/Bundle/Application/07F5BD7B-283E-42BD-8F2D-9EE6B6772B46/Carnets-sci.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/mobile/Containers/Data/Application/EEF85416-2409-4FDE-8D41-3256A66AB65C/tmp/pip-build-env-ve9lr31y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel

  Using cached scikit-image-0.18.2.tar.gz (30.8 MB)

      return self._get_build_requires(
    File "/private/var/mobile/Containers/Data/Application/EEF85416-2409-4FDE-8D41-3256A66AB65C/tmp/pip-build-env-ve9lr31y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/private/var/mobile/Containers/Data/Application/EEF85416-2409-4FDE-8D41-3256A66AB65C/tmp/pip-build-env-ve9lr31y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/mobile/Containers/Data/Application/EEF85416-2409-4FDE-8D41-3256A66AB65C/tmp/pip-build-env-ve9lr31y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 14, in <module>

**Comment by holzschu** [comment]
Yes, scikit-image has some C and Cython modules, so it cannot be installed by the user (since there are no C compilers embedded on iOS). I’ll try to install it at the app level.

**Comment by zgw521** [comment]
Wow, thanks a lot for your prompt and detail explanation! I appreciate! Anyway, Carnets is an amazing App.
