### ISSUE TITLE
scikit-image install/include

### ISSUE THREAD

**Issue by dieserobin** [holzschu/Carnets#267]
Unfortunately I am unable to install scikit-image. It gives me an erred when I try %pip install scikit-image

error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      setup.py:9: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.command.build_ext import build_ext as npy_build_ext
      Traceback (most recent call last):
        File "/private/var/containers/Bundle/Application/5C9A7250-3758-41DF-B53D-091F07A4B87C/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/private/var/containers/Bundle/Application/5C9A7250-3758-41DF-B53D-091F07A4B87C/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/private/var/containers/Bundle/Application/5C9A7250-3758-41DF-B53D-091F07A4B87C/Carnets.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/containers/Bundle/Application/5C9A7250-3758-41DF-B53D-091F07A4B87C/Carnets.app/Library/lib/python3.9/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/containers/Bundle/Application/5C9A7250-3758-41DF-B53D-091F07A4B87C/Carnets.app/Library/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/containers/Bundle/Application/5C9A7250-3758-41DF-B53D-091F07A4B87C/Carnets.app/Library/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 20, in <module>
          from pythran.dist import PythranBuildExt as pythran_build_ext
      ModuleNotFoundError: No module named 'pythran'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.1.2 -> 22.3

**Comment by dieserobin** [comment]
updating pip did not help

**Comment by holzschu** [comment]
Even though the error message is not very clear, the main issue is that scikit-image has components written in C, and there are no C compilers available on iOS.
I'm in the process of updating all the packages, I'll see if I manage to cross-compile scikit-image as well.
