### ISSUE TITLE
SimpleITK

### ISSUE THREAD

**Issue by Nicolaeus** [holzschu/Carnets#315]
Defaulting to user installation because normal site-packages is not writeable
Collecting simpleitk
  Downloading SimpleITK-2.1.1.2.tar.gz (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 5.0 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: simpleitk
  Building wheel for simpleitk (pyproject.toml): started
  Building wheel for simpleitk (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error
  

Failed to build simpleitk

  × Building wheel for simpleitk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/DFC8B3A9-6316-49EC-8A77-53F902881EFC/Carnets-sci.app/Library/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-build-env-nxar16cc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-build-env-nxar16cc/overlay/lib/python3.11/site-packages/setuptools

          self.run_setup()
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-build-env-nxar16cc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
        File "/private/var/mobile/Containers/Data/Application/215DDBCB-76A7-41AB-9C97-9B17FEAAD2F6/tmp/pip-build-env-nxar16cc/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 583, in setup
          assert machine in {"x86_64", "arm64", "universal2"}, f"macOS arch {machine} not understood"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError: macOS arch iPad14,6 not understood
      [end of output]

**Comment by holzschu** [comment]
It's simple: inside Carnets, you can only use pip to install pure-Python packages (packages that only contain Python files as source code). Anything that contains binaries (executables, dynamic libraries) will not work.
