### ISSUE TITLE
Wget module install failed

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#74]
!pip install wget
Collecting wget
  Downloading https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
Installing collected packages: wget
ERROR: Error checking for conflicts.
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _dep_map
  Running setup.py install for wget ... done
Successfully installed wget-3.2
    return self.__dep_map
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3003, in _parsed_pkg_info
    return self._pkg_info
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 524, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 47, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in requires
    dm = self._dep_map
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3005, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1419, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1607, in _get

**Comment by holzschu** [comment]
Hi, 
out of curiosity, what does "!pip show wget" shows?

**Comment by ifuchs** [comment]
!pip show wget
ERROR: Exception:
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _dep_map
    return self.__dep_map
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/CF02358E-FDAA-4467-9797-196F7182DCB1/Library/lib/python3.7/site-packages/pip/_vendor/pkg_r

OK, I guess I can't add it myself?

**Comment by ifuchs** [comment]
Although pip install Wget works fine on the Mac

**Comment by holzschu** [comment]
`!pip show wget` shows that is installed on my device. So it can be done, but I don't remember how I did it...

**Comment by holzschu** [comment]
I tried on a different device, and `!pip install wget`works.
Your error message mentions the function `_warn_about_conflicts`, so this may be caused by another package conflicting with wget. But still, this should not cause an exception. I'm investigating.

**Comment by suriyanarasimman** [comment]
Hey did anyone find a solution for this? 
I tried it in my iPad 10th gen and I was not able to use wget or any other commands as well like ls, pwd, unzip etc.

![image](https://user-images.githubusercontent.com/42350458/217514572-af649c4a-7771-4a24-b004-e7bbd854f93a.jpeg)

**Comment by suriyanarasimman** [comment]
Hey thanks for the fast reply, yes there was a space between ! And command so now ls and pwd is working.

But when I use curl to download, this is the error I get.

![image](https://user-images.githubusercontent.com/42350458/217518565-72228c8e-fe26-4f0e-b2c8-ccc69decff10.jpeg)

And unzip was not working is there any alternative for that?

**Comment by holzschu** [comment]
I think curl with no arguments is sending the file to the standard output, which is not what you want here. The syntax is `curl [url] -O` to save the remote file to a local file with the same name, e.g. `curl http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_vi.tar.gz -O`.

Since the archive you are downloading is `.tar.gz`, it should be unpacked with `tar`: `tar -xzf aclImdb_vi.tar.gz`.

**Comment by suriyanarasimman** [comment]
Thanks it is working now! Btw is there any plan to include either PyTorch or tenser-flow to carnets?

**Comment by holzschu** [comment]
It's on the todo list, yes, but it's going to be difficult (the more complicated a framework is, the harder it is to cross-compile it). We do have scikit-learn, which can do some similar things, but not all of them.
