### ISSUE TITLE
Add xarray

### ISSUE THREAD

**Issue by hammer** [holzschu/Carnets#80]
It would be nice to have https://github.com/pydata/xarray on Carnets. I tried to install with `!pip install xarray` but I got the following error (sorry for the funky formatting):

> ERROR: Complete output from command /var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/bin/python3 /var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/tmp/tmpfus0xv5r:
>   ERROR: Traceback (most recent call last):
>     File "/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
>       main()
>     File "/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
>       backend = _build_backend()
>     File "/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 31, in _build_backend
>       ep = os.environ['PEP517_BUILD_BACKEND']
>     File "/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/os.py", line 680, in __getitem__
>       raise KeyError(key) from None
>   KeyError: 'PEP517_BUILD_BACKEND'
> ERROR: Command "/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/bin/python3 /var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/tmp/tmpfus0xv5r" failed with error code 1 in /private/var/mobile/Containers/Data/Application/B777AD84-D1AE-42AB-9601-23E109F645F5/tmp/pip-install-tvaed_yf/pandas

**Comment by holzschu** [comment]
It should be able to install, since scipy is an optional dependency. I've added it to the the list. https://github.com/holzschu/Carnets/projects/1

**Comment by holzschu** [comment]
So, I checked and tried. 

The current version of xarray requires a pandas with version >= 0.25, and Carnets has version 0.24.2. So pip tries to install the latest pandas version, and fails because it cannot compile it.

You can force pip to install the previous version with `!pip install xarray==0.14.1` (that is the version of November 19, 2019, instead of January 30, 2020).

You can also force pip to install the latest version of xarray with `!pip install xarray --no-dependencies`, but I do not recommend it.

**Comment by holzschu** [comment]
Hi, 
"%pip install xarray" now works with the latest TestFlight version (soon to be the AppStore version).
