### ISSUE TITLE
Cannot install sqlalchemy

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#89]
i am trying to pip install sqlalchemy but it fails with:

`ERROR: Complete output from command /var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/bin/python3 /var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/tmprd_ol6vi:
  ERROR: Traceback (most recent call last):
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 31, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/os.py", line 680, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/bin/python3 /var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/tmprd_ol6vi" failed with error code 1 in /private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/pip-install-h7gd8kjl/sqlalchemy`

**Comment by holzschu** [comment]
I have not tested this, but the sqlalchemy documentation says that you can issue the command `setenv DISABLE_SQLALCHEMY_CEXT 1` before running `pip install` and it won't even try to compile the C extensions.

**Comment by ifuchs** [comment]
I just tried as you suggest and after issuing the command an Redding the
pip. Install, got:


ERROR: Complete output from command
/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/bin/python3
/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py
get_requires_for_build_wheel
/private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/tmpu_p__oz7:
 ERROR: Traceback (most recent call last):
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py",
line 207, in <module>
      main()
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py",
line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py",
line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py",
line 31, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/os.py",
line 680, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------ERROR: Command
"/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/bin/python3
/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py
get_requires_for_build_wheel
/private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/tmpu_p__oz7"
failed with error code 1 in
/private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/pip-install-edwvptv0/sqlalchemy

**Comment by holzschu** [comment]
Hi, 
on the latest TestFlight version, `!pip install sqlalchemy` gives a lot of warnings because it first tries to install the C extensions and fails, but ultimately installs the package (without the C extensions).
