### ISSUE TITLE
Cannot install plotnine

### ISSUE THREAD

**Issue by ifuchs** [holzschu/Carnets#90]
I'm to install plotnine and the following error result:

` ERROR: Complete output from command /var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/bin/python3 /var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/tmppem74svk:
  ERROR: Traceback (most recent call last):
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 31, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/os.py", line 680, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command "/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/bin/python3 /var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/tmppem74svk" failed with error code 1 in /private/var/mobile/Containers/Data/Application/415FE8A3-9150-4DC4-BB74-03B29A13F6B5/tmp/pip-install-ia1ybp23/statsmodels `

**Comment by holzschu** [comment]
Hi, 
`plotnine` depends on `scipy`, so this is now added to the list of packages to install once `scipy` is installed.

**Comment by holzschu** [comment]
Note for myself: plotnine also depends on statsmodels. Retry installation once statsmodels is installed: https://github.com/holzschu/Carnets/issues/100
