### ISSUE TITLE
Cannot install shapely

### ISSUE THREAD

**Issue by bockstaller** [holzschu/Carnets#99]
Trying to install shapely with

```
%pip install shapely 
```

results in the following output:

```
Collecting shapely
  Downloading https://files.pythonhosted.org/packages/44/ec/4eddbf9d17a917c51fb4ad159aa7137f506681e91ab559cf87d120e1d78d/Shapely-1.7.0.tar.gz (349kB)
     |████████████████████████████████| 358kB 779kB/s eta 0:00:01

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/mobile/Containers/Data/Application/AA301BDF-0B32-4798-984F-F0BD8CB18A98/tmp/pip-install-8qsopb6y/shapely/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/private/var/mobile/Containers/Data/Application/AA301BDF-0B32-4798-984F-F0BD8CB18A98/tmp/pip-install-8qsopb6y/shapely/shapely/_buildcfg.py", line 89, in <module>
        clibs = get_geos_config('--clibs')
      File "/private/var/mobile/Containers/Data/Application/AA301BDF-0B32-4798-984F-F0BD8CB18A98/tmp/pip-install-8qsopb6y/shapely/shapely/_buildcfg.py", line 78, in get_geos_config
        raise ValueError(stderr.strip())
    ValueError: b'geos-config: command not found'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/mobile/Containers/Data/Application/AA301BDF-0B32-4798-984F-F0BD8CB18A98/tmp/pip-install-8qsopb6y/shapely/

Note: you may need to restart the kernel to use updated 
packages. ```

PS: Thanks for this wonderful app ❤️

**Comment by holzschu** [comment]
Hi, yes, shapely requires the geos library to be installed as a prerequisite. And geos requires a C compiler, so that's going to take time. If I remember correctly shapely and geos are also required for cartopy which is on the todo list.
